stages:
  - deploy

variables:
  DEPLOY_PATH: "/home/sites/25a/3/3af37bad2e/public_html"  # Chemin exact fourni par l'hébergeur
  SERVER_USER: "sgrosrey.fr"
  SERVER_IP: "ssh.gb.stackcp.com"

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -y && apt-get install -y openssh-client rsync git unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-progress --no-interaction --prefer-dist

deploy_production:
  stage: deploy
  only:
    - dev  # Déclenche uniquement sur la branche principale
  before_script:
    # Configuration SSH
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
  script:
    # Commandes de déploiement
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd $DEPLOY_PATH &&
        git pull origin main &&
        composer install --no-dev --optimize-autoloader &&
        php bin/console cache:clear --env=prod &&
        php bin/console doctrine:migrations:migrate --no-interaction
      "