image: php:8.2

stages:
  - deploy

variables:
  DEPLOY_PATH: "/home/sites/25a/3/3af37bad2e/public_html"
  SERVER_USER: "sgrosrey.fr"
  SERVER_IP: "ssh.gb.stackcp.com"

deploy_production:
  stage: deploy
  only:
    - dev   # ou main selon ta branche
  before_script:
    - apt-get update -y && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd $DEPLOY_PATH &&
        git pull origin dev &&
        composer install --no-dev --optimize-autoloader &&
        php bin/console cache:clear --env=prod
      "
